export const PROFILE_ROUTE = '/profile'
export const DIALOGS_ROUTE = '/dialogs'
export const NEWS_ROUTE = '/news'
export const MUSIC_ROUTE = '/music'
export const SETTINGS_ROUTE = '/settings'
export const FRIENDS_ROUTE = '/friends'
export const FIND_FRIENDS_ROUTE = '/find-friends'